### PR TITLE
Automatic validation with Travis CI, fixes #12

### LINKED ISSUE #12: Validate with continuous integration
It'd be nice to automatically validate the XML on every commit, using a service like [Travis CI](https://travis-ci.org/), so that any errors can be flagged as they're created. This will be even more useful if we gain more contributors. Travis's integration with GitHub will allow us to see at a glance whether a pull request breaks validation in some way, e.g. if it's missing end tags. 

The CI script will probably need to be able to read the whole project as one XML file. We could do this either by writing a header and footer, and having the script concatenate all the files, or by having the header file include the episodes using something like [XInclude](https://en.wikipedia.org/wiki/XInclude). Since the second solution sounds a little cleaner, I'll starting working on that.

### PR DESCRIPTION
**Pull request by JonathanReeve**
I thought I'd open a pull request for these changes, since they're big changes. This enables automatic validation against the TEI P5 DTD, using Travis CI. Every time we push to master (or to any branch), Travis will check out a copy, install the command-line validator `xmllint`, and validate `header.xml` against `schema/tei_all.dtd`. The output of this validation will appear on [the Travis page for this repo](https://travis-ci.org/JonathanReeve/corpus-joyce-ulysses-tei). If all is well, it should report "build passing." If not, it will report "build failing," and errors will be available for view on the Travis site. 

Some notable changes here: 

 - I had to rename `u10_wandering rocks.xml` to `u10_wandering_rocks.xml`, since the space in the filename was causing errors in xinclude. I hope this is OK, and doesn't cause too many conflicts.
 - I replaced all ampersands with `&amp;` so that they'd be valid XML. XML thinks that any word that begins with an ampersand is an entity, and so it complains that it has no semicolon. 
 - I wrapped each episode in `<div type="episode" n="01">`, since every XML page apparently has to have a root element, or else it can't be parsed by xinclude. We can change this syntax, if we want.

If everything looks good, let me know, and I'll go ahead and merge this.

### CODE REVIEW

**Comment by yellwork** [comment]
That all sounds great, Jonathan. If you want to merge, I’ll go ahead and make a few changes and then commit to the master branch and check out the Travis page.

> The output of this validation will appear on the Travis page for this repo. If all is well, it should report "build passing." If not, it will report "build failing," and errors will be available for view on the Travis site.

This means a non-validating will still push, right? But that the contributor can be alerted to validation errors newly introduced if s/he checks the Travis page?

One cosmetic question: is it worth renaming the episode files to just 'u01' through 'u18'? Or does having the Homeric titles in place aid user navigation? (If the latter, should we also expand 'u14_oxen.xml' to 'u14_oxen_of_the_sun.xml'?)

**Comment by JonathanReeve** [comment]
Non-validating commits, if pushed by a contributor with push access, will still push, but the repo will then be marked as "build failing." Pull requests will behave the same way--the green "merge pull request" button will become red for failing builds, alerting us that a new contribution has non-validating markup in it. 

I'll go ahead and merge this, then. Feel free to test it by pushing junk markup, and then correcting it. 

I think keeping the filenames as-is is fine. Renaming "Oxen of the Sun" might help contributors to understand what episode it is, so I'd be in favor of that change.

**Comment by yellwork** [comment]
> Travis#28 failed

I just checked the errors being reported:

> No declaration for attribute said of element said

Ah. How do we get around this? Do we have to start adding the `@who` values to the header?

**Comment by yellwork** [comment]
Ignore the previous comment. I caught the error:

```xml
<lb n="010483"/><said said="Haines">―That one about the cracked lookingglass of a servant being the symbol of
<lb n="010484"/>Irish art is deuced good.</said></p>

```

This is now:

```xml
<lb n="010483"/><said who="Haines">
```

**Comment by yellwork** [comment]
I just updated the URL for Travis CI validation on the README.md. It now points to https://travis-ci.org/open-editions/corpus-joyce-ulysses-tei. I noticed the project is no longer validating, however: is that on account of something I did in the latest round of my edits? Or is there something amiss in the Header?

**Pull request merged**
